// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Filters - An array of filters are used to query requests.
type Filters struct {
	// A list of filters to apply to the query.
	Filters []Filter `json:"filters"`
	// The maximum number of results to return.
	Limit int64 `json:"limit"`
	// The offset to start the query from.
	Offset int64 `json:"offset"`
}
