// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Filter - Filters are used to query requests.
type Filter struct {
	Field     string `json:"field"`
	Matchtype string `json:"matchtype"`
	Value     string `json:"value"`
}
