// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Success - The `Status` type defines a successful response.
type Success struct {
	Success *bool `json:"success,omitempty"`
}
