// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// UserInput - The details of a typical user account
type UserInput struct {
	Country   string `json:"country"`
	Email     string `json:"email"`
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
	Nickname  string `json:"nickname"`
	Password  string `json:"password"`
}

// User - The details of a typical user account
type User struct {
	Country    string     `json:"country"`
	Createdate *time.Time `json:"createdate,omitempty"`
	Email      string     `json:"email"`
	Firstname  string     `json:"firstname"`
	ID         *string    `json:"id,omitempty"`
	Lastname   string     `json:"lastname"`
	Nickname   string     `json:"nickname"`
	Password   string     `json:"password"`
	Updatedate *time.Time `json:"updatedate,omitempty"`
}
