// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"AcmeTerraform/internal/sdk/pkg/models/shared"
	"net/http"
)

type DeleteUserv1Request struct {
	// UserID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type DeleteUserv1Response struct {
	ContentType string
	// Default error response
	Error       *shared.Error
	StatusCode  int
	RawResponse *http.Response
	// OK
	Success *shared.Success
}
