// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"AcmeTerraform/internal/sdk/pkg/models/shared"
	"net/http"
)

type SearchUsersv1Response struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	Users *shared.Users
}
