// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"AcmeTerraform/internal/sdk/pkg/models/shared"
	"net/http"
)

type UpdateUserv1Request struct {
	UserInput shared.UserInput `request:"mediaType=application/json"`
	// UserID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type UpdateUserv1Response struct {
	ContentType string
	// Default error response
	Error       *shared.Error
	StatusCode  int
	RawResponse *http.Response
	// OK
	User *shared.User
}
